# Generated by Django 5.2.1 on 2025-05-14 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="brand",
            options={"verbose_name": "Бренд", "verbose_name_plural": "Бренд"},
        ),
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Кадегории", "verbose_name_plural": "Категории"},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "Товары", "verbose_name_plural": "Товары"},
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Цена"
            ),
        ),
    ]
